export const downloadCSV = (data: any[], filename: string) => {
  if (data.length === 0) {
    alert("No data to download");
    return;
  }

  const headers = Object.keys(data[0]);
  const csvContent = [
    headers.join(","),
    ...data.map((row) =>
      headers
        .map((header) => {
          const val = row[header];
          // Escape quotes and handle commas
          const cell = val === null || val === undefined ? "" : String(val).replace(/"/g, '""');
          return cell.includes(",") || cell.includes('"') || cell.includes("\n") ? `"${cell}"` : cell;
        })
        .join(",")
    ),
  ].join("\n");

  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  if (link.download !== undefined) {
    const url = URL.createObjectURL(blob);
    link.setAttribute("href", url);
    link.setAttribute("download", filename);
    link.style.visibility = "hidden";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }
};

export const downloadPDF = (title: string, data: any[], filename: string) => {
  if (data.length === 0) {
    alert("No data to download");
    return;
  }

  const headers = Object.keys(data[0]);
  const htmlContent = `
    <html>
      <head>
        <title>${title}</title>
        <style>
          body { font-family: sans-serif; padding: 20px; }
          h1 { text-align: center; color: #333; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
          th { background-color: #f4f4f4; font-weight: bold; }
          tr:nth-child(even) { background-color: #fafafa; }
          .footer { margin-top: 30px; font-size: 10px; color: #666; text-align: center; }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <p>Generated on: ${new Date().toLocaleString()}</p>
        <table>
          <thead>
            <tr>
              ${headers.map(h => `<th>${h}</th>`).join('')}
            </tr>
          </thead>
          <tbody>
            ${data.map(row => `
              <tr>
                ${headers.map(h => {
                  const val = row[h];
                  const text = String(val).trim();
                  const isNegative = text.startsWith('-') || text.startsWith('₹-') || text.startsWith('-₹');
                  const isPositive = text.startsWith('+') || text.startsWith('₹+') || text.startsWith('+₹');
                  const color = isNegative ? '#e11d48' : isPositive ? '#059669' : 'inherit';
                  return `<td style="color: ${color}">${val}</td>`;
                }).join('')}
              </tr>
            `).join('')}
          </tbody>
        </table>
        <div class="footer">
          Generated by School Manager System
        </div>
      </body>
    </html>
  `;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    // Wait for content to load then print
    printWindow.onload = () => {
      printWindow.print();
      // Optionally close after print
      // printWindow.close();
    };
  } else {
    alert("Please allow popups to download PDF");
  }
};

/**
 * Download any JSON-serializable data as a .json file.
 */
export const downloadJSON = <T = unknown>(data: T, filename: string) => {
  const json = JSON.stringify(data, null, 2);
  const blob = new Blob([json], { type: "application/json;charset=utf-8;" });
  const link = document.createElement("a");
  if (link.download !== undefined) {
    const url = URL.createObjectURL(blob);
    link.setAttribute("href", url);
    link.setAttribute("download", filename);
    link.style.visibility = "hidden";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
};

/**
 * Copy JSON-serializable data to clipboard as formatted JSON.
 * Returns a Promise<boolean> indicating success.
 */
export const copyJSONToClipboard = async <T = unknown>(data: T): Promise<boolean> => {
  const json = JSON.stringify(data, null, 2);
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(json);
      return true;
    }
    const ta = document.createElement("textarea");
    ta.value = json;
    ta.style.position = "fixed";
    ta.style.left = "-9999px";
    ta.style.top = "-9999px";
    ta.setAttribute("readonly", "");
    document.body.appendChild(ta);
    ta.select();
    ta.setSelectionRange(0, json.length);
    const ok = document.execCommand("copy");
    document.body.removeChild(ta);
    return ok;
  } catch {
    return false;
  }
};
